alias wts='wt switch'
alias wtc='wt switch --create'
alias wtl='wt list --full'
alias wtr='wt remove'
alias wtv='wt config state vars set'
alias wtvl='wt config state vars list'
alias wtlogs='wt config state logs'
alias wtlog='cat "$(find "$(realpath "$(git rev-parse --git-common-dir)")/wt-logs" -name "*.log" -size +0 -print0 | xargs -0 ls -t | head -1)"'
