" DO NOT EDIT THIS FILE
" File generated when the following is run:
" $	sh ~/.vim_runtime/install_awesome_vimrc.sh

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
try
  source ~/.my_vimrc
catch
endtry
