alias gl='git pull --prune'
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gp='git push origin HEAD'
alias gd='git diff --color | sed "s/^\([^-+ ]*\)[-+ ]/\\1/" | less -r'
alias gc='git commit'
alias gca='git commit -a'
alias gco='git checkout'
alias gcb='git copy-branch-name'
alias gb='git branch'
alias gs='git status -sb'
alias gac='git add -A && git commit -m'
alias ge='git-edit-new'
alias gcnm='git commit --no-verify -m'
alias gsa='git stage .'
alias gcan='git commit --amend --no-edit'
alias grs1='git reset --soft HEAD~1'
alias gst='git stash'
alias gss='git stash show -p'
alias gsp='git stash pop'

alias lzg='lazygit'
