alias gl='git pull --prune'
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gp='git push origin HEAD'
alias gcpb='git copy-branch-name'
alias gs='git status -sb'
alias gac='git add -A && git commit -m'
alias ge='git-edit-new'
alias gcnm='git commit --no-verify -m'
alias gsa='git stage .'
alias gcan='git commit --amend --no-edit'
alias grs1='git reset --soft HEAD~1'
alias gstS='git stash push --staged'
alias gstk='git stash push --keep-index'

alias lzg='lazygit'
